name: "Jira ticket creator"
description: "Creater a Jira ticket"
inputs:
  github_token:
    description: "GitHub token"
    required: true
  jira_url:
    description: "URL of Jira instance"
    required: true
  account:
    description: "Jira account"
    required: true
  password:
    description: "Account password"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
