name: "Jira ticket creator"
description: "Creater a Jira ticket"
inputs:
  github_token:
    description: "GitHub token"
    required: true
  jira_host:
    description: "Jira server"
    required: true
  jira_username:
    description: "Jira account"
    required: true
  jira_password:
    description: "Account password"
    required: true
  ticket_prefix:
    description: "Jira ticket prefix"
    required: true
  ticket_descriptor:
    description: "Text before ticket link in release notes"
    default: "Ticket"
    required: false
  configuration_file:
    description: "Path for field mapping configuration"
    default: ".github/jira-config.yml"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
