name: Create Jira ticket

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
      type:
        description: 'create/update'
        required: true
      status:
        description: 'Ticket status for update action'
        required: false

jobs:
  create_ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create ticket
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ticket_prefix: EVI
          jira_host: atlas.elisa.fi/jira
          ticket_descriptor: "Muha"
